Minor changes and improvements
rzach/sets-logic-computation pull request #1
Opened 2017-01-28 05:22 UTC by Buddybenj

2017-01-28 05:23 UTC, Buddybenj commented on include/summary-4.tex
> +uncountable set~$Y$ with an element of~$X$ in an injective way. If this
Please confirm if this change is correct.

2017-01-28 21:20 UTC, rzach requested changes

2017-01-28 21:20 UTC, rzach commented on include/summary-4.tex
> +uncountable set~$Y$ with an element of~$X$ in an injective way. If this
It is correct, but not in line with the section being summarized (although neither was the old version). It should be "by associating every element of~$X$ with an element of some known uncountable set~$Y$ in a surjective way."

2017-01-28 21:20 UTC, rzach commented on include/summary-2.tex
> -equal to, evenly dividing, being the same length, being a subset of,
Can you leave in the first "being" (the "evenly dividing" sortof cancels the repetition of "being" if that makes sense).

2017-01-28 21:40 UTC, rzach approved these changes

2017-01-31 23:48 UTC, rzach commented
Thanks for suggesting these changes. I'm not sure how GitHub wants me/you to make changes to the pull request. Perhaps by "approving the requested changes" I indicated that the pull request is now ready to merge instead of indicating that I agreed (with myself!) that these changes should be made. Let me know if you see a way to change the pull request (ie change your changes) or if I should do it.

2017-02-01 07:49 UTC, Buddybenj commented
I made the requested changes. As long as there are no glaring errors, feel free to merge.

2017-02-01 17:06 UTC, merged

2017-02-01 17:06 UTC, rzach commented
Thanks again!